contributers.md
Hey, lets maintain a list of contributors!
=> Adding Contributors list file

cpp/Print Series.cpp, cpp/Print reverse.cpp, cpp/Simple Input.cpp, cpp/TemperatureConverterforGivenRange.cpp, cpp/Trailing Zeros Function.cpp, cpp/Von Neuman Loves Binary.cpp
This are some solved challenge programs by coding Blocks.
=> Added Files

C codes/AbsoluteNumber.c, C codes/Armstrong.c, C codes/CapitalorSmall.c, C codes/Reverse.c, C codes/SumAve.c, C codes/SumOfDigits.c, C codes/factorial.c, C codes/palindrome.c, C codes/pattern.c, C codes/pattern1.c, C codes/pattern2.c, C codes/pattern3.c, C codes/pattern4.c, C codes/pattern5.c, C codes/pattern6.c, Cpp codes/tic tac toe.cpp
Hi, Please merge my PR and help me contribute open source
=> added various programs

README.md
Hey! I added some gifs and updated code of conduct
=> Updated Readme.md file by updating code of conduct

Cpp codes/Soduko Solver.cpp
=> soduko solver added using c++

Cpp codes/ROT 13 Caesar Cipher.cpp
I added a C++ code to decode Rot 13 encoded text 
I hope this helps to increase knowledge about programs.
=> Rot 13 Caesar Cipher

Py_Codes/SelectionSort.py
Added Selection sort code under /PY_CODES ( with appropriate comments and explanations )
=> Added SelectionSort.py under /PY_CODES

JavaScript/mergeSortedArrays.js
Issue #1 : Added JS Snippet to merge sorted Arrays. Hope this helps !!
=> chore: Added new JS Code Snippet for Merge Sorted Arrays

Dart/HelloWorld.dart, Dart/built_in_data_types.dart, Dart/constants.dart, Dart/string_and_string_interpolation.dart
I have added code of it which was assigned to me at issue no. #61
=> Added Folder of Dart and Some Code of it

Shell/mmap.sh
I know this is basic, but I have seen a few friends that didn't know that Nmap can be used in Metasploit, so I thought to help!
=> Metasploit with nmap!

Cpp codes/Simple_Insane_Patt.cpp
It consists of two triangles one inverted right triangle and one right-angled both inclined to each other!
=> This is simple triangle pattern!

HTML/simple_Form_page.html
This is an example of a Form Filling Page!
=> Zoo Keeper Sign In Form

SQL/main.sql
This is SQL commands basically used at DBMS, and website back-end also.
=> SQL Commands!

Dart/basic-if-else.dart, Dart/basic-loop.dart
I'm adding some of new syntax in dart language
=> Adding some basic syntax in dart

Dart/check if elements in a list are equal or not.dart, Dart/largest and smallest values in a list.dart, Dart/pattern printing triangle.dart, Dart/sort elements.dart
I have add the following Dart programs in the Dart folder:
1) Dart program to check if two programs are equal element by element.
2) Dart program to sort an integer list.
3) Dart program to find the minimum and maximum elements in a list.
4) Dart program to print a pattern as follows.
*
* *
* * *
* * * *
* * * * *
* * * * * *
=> Added programs in dart language

Py_Codes/linked_list.py
Coded a basic linked list with Node and LinkedList Classes. There are three simple methods in the LinkedList class, namely - 1) append(self, value), 2) delete_end(self), and 3) __repr__(self). The use cases of the first two are self explanatory and the last one is responsible for printing legible data to the screen whenever the inbuilt print function is called on an object of the LinkedList class. All the edge cases have been taken into consideration!
=> Added code for linked list

C++ codes/quicksort.cpp
=> Quick Sort

C codes/ Medium/Recursive C program to compute atoi().c, Cpp codes/ Medium/check whether a string makes an additive sequence.cpp
Recursive C program to compute atoi() - hacktoberfest
=> Recursive C program to compute atoi()

java/InsertionSort.java
InsertionSort.java code is modified and fixed some errors.
=> Modified Code

README.md
=> fixed links on README

C++ codes/spiral array.cpp
=> add spiral array

JavaScript/Medium/rotatedSortedArray.js
solved rotated sorted array problem in javascript
[33. Search in Rotated Sorted Array ](https://leetcode.com/problems/search-in-rotated-sorted-array/)
=> rotated sorted array leetcode javascript

C codes/ Medium/Automatedbill.c, C codes/ Medium/bill.txt
Program to automatacally print the bill of the customer using File operations.
=> Added a c program which prints the bill automatically in a txt file
